sudo: reuqired
services:
    - docker
before_install:
    - docker build -t klisowski2016/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true klisowski2016/react-test npm test -- --coverage

after_sucess:
    - docker build -t klisowski2016/multi-client ./client
    - docker build -t klisowski2016/multi-nginx ./nginx
    - docker build -t klisowski2016/multi-server ./server
    - docker build -t klisowski2016/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push klisowski2016/multi-client
    - docker push klisowski2016/multi-nginx
    - docker push klisowski2016/multi-server
    - docker push klisowski2016/multi-worker

